services:
  backend:
    build: backend/
    container_name: food_planner_backend
    restart: always 
    environment:
      ENV: production
    volumes:
      - /var/lib/food_planner:/var/lib/food_planner
      - /var/log/food_planner:/var/log/food_planner
    ports:
      - "8000:8000"