"""add_job_type_to_jobrun

Revision ID: 2e3a9cd22a2e
Revises: d930e0211fbb
Create Date: 2025-07-31 19:39:44.885531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3a9cd22a2e'
down_revision: Union[str, None] = 'd930e0211fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIPPING INDEX CHANGES FOR NOW - keeping food indexes as-is
    # op.drop_index('ix_food_food_provider', table_name='food')
    # op.drop_index('ix_food_new_date', table_name='food')
    # op.drop_index('ix_food_new_food_provider', table_name='food')
    # op.drop_index('ix_food_new_name', table_name='food')
    # op.create_index(op.f('ix_food_food_vendor'), 'food', ['food_vendor'], unique=False)
    
    # Add job_type column with default value
    op.add_column('jobrun', sa.Column('job_type', sa.Enum('FOOD_DATA_COLLECTION', 'DATABASE_BACKUP', name='jobtype'), nullable=False, server_default='FOOD_DATA_COLLECTION'))
    
    # Update existing records to have the default job type (all existing jobs are food data collection)
    op.execute("UPDATE jobrun SET job_type = 'FOOD_DATA_COLLECTION' WHERE job_type IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobrun', 'job_type')
    # SKIPPING INDEX CHANGES - keeping as-is
    # op.drop_index(op.f('ix_food_food_vendor'), table_name='food')
    # op.create_index('ix_food_new_name', 'food', ['name'], unique=False)
    # op.create_index('ix_food_new_food_provider', 'food', ['food_vendor'], unique=False)
    # op.create_index('ix_food_new_date', 'food', ['date'], unique=False)
    # op.create_index('ix_food_food_provider', 'food', ['food_vendor'], unique=False)
    # ### end Alembic commands ###
