"""move_job_specific_fields_to_details_json

Revision ID: 8e21735b3345
Revises: 2e3a9cd22a2e
Create Date: 2025-07-31 20:03:03.716879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e21735b3345'
down_revision: Union[str, None] = '2e3a9cd22a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIPPING INDEX CHANGES FOR NOW - keeping food indexes as-is
    # op.drop_index('ix_food_food_provider', table_name='food')
    # op.drop_index('ix_food_new_date', table_name='food')
    # op.drop_index('ix_food_new_food_provider', table_name='food')
    # op.drop_index('ix_food_new_name', table_name='food')
    # op.create_index(op.f('ix_food_food_vendor'), 'food', ['food_vendor'], unique=False)
    
    # Add details column first
    op.add_column('jobrun', sa.Column('details', sa.JSON(), nullable=True))
    
    # Migrate existing data from columns to JSON
    op.execute("""
        UPDATE jobrun 
        SET details = json_object(
            'food_vendor', food_vendor,
            'week', week,
            'year', year
        )
        WHERE job_type = 'FOOD_DATA_COLLECTION'
    """)
    
    # Now drop the old columns
    op.drop_column('jobrun', 'week')
    op.drop_column('jobrun', 'food_vendor')
    op.drop_column('jobrun', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the old columns
    op.add_column('jobrun', sa.Column('year', sa.INTEGER(), nullable=True))
    op.add_column('jobrun', sa.Column('food_vendor', sa.VARCHAR(), nullable=True))
    op.add_column('jobrun', sa.Column('week', sa.INTEGER(), nullable=True))
    
    # Migrate data back from JSON to columns
    op.execute("""
        UPDATE jobrun 
        SET 
            food_vendor = json_extract(details, '$.food_vendor'),
            week = json_extract(details, '$.week'),
            year = json_extract(details, '$.year')
        WHERE job_type = 'FOOD_DATA_COLLECTION' AND details IS NOT NULL
    """)
    
    # Make columns NOT NULL after data migration
    op.alter_column('jobrun', 'food_vendor', nullable=False, server_default=sa.text("'CITY_FOOD'"))
    op.alter_column('jobrun', 'week', nullable=False)
    op.alter_column('jobrun', 'year', nullable=False)
    
    # Drop details column
    op.drop_column('jobrun', 'details')
    
    # SKIPPING INDEX CHANGES - keeping as-is
    # op.drop_index(op.f('ix_food_food_vendor'), table_name='food')
    # op.create_index('ix_food_new_name', 'food', ['name'], unique=False)
    # op.create_index('ix_food_new_food_provider', 'food', ['food_vendor'], unique=False)
    # op.create_index('ix_food_new_date', 'food', ['date'], unique=False)
    # op.create_index('ix_food_food_provider', 'food', ['food_vendor'], unique=False)
    # ### end Alembic commands ###
