"""Add provider column with default to Food model

Revision ID: c12632783e4c
Revises: 
Create Date: 2025-03-29 19:11:35.495522

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c12632783e4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "food_new",
        sa.Column("food_id", sa.Integer(), primary_key=True),
        sa.Column("date", sa.Date(), primary_key=True, index=True),
        sa.Column("food_provider", sa.String(), primary_key=True, nullable=False, index=True),
        sa.Column("name", sa.String(), nullable=False, index=True),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein", sa.Integer(), nullable=False),
        sa.Column("carb", sa.Integer(), nullable=False),
        sa.Column("fat", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
    )

    op.execute("""
        INSERT INTO food_new (food_id, date, food_provider, name, calories, protein, carb, fat, price)
        SELECT food_id, date, 'CITY_FOOD', name, calories, protein, carb, fat, price FROM food
    """)

    op.drop_table("food")
    op.rename_table("food_new", "food")

    op.create_index('ix_food_date', 'food', ['date'])
    op.create_index('ix_food_name', 'food', ['name'])
    op.create_index('ix_food_food_provider', 'food', ['food_provider'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('jobrun',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('timestamp', sa.DATETIME(), nullable=False),
    # sa.Column('week', sa.INTEGER(), nullable=False),
    # sa.Column('year', sa.INTEGER(), nullable=False),
    # sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('food',
    # sa.Column('food_id', sa.INTEGER(), nullable=False),
    # sa.Column('date', sa.DATE(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('calories', sa.INTEGER(), nullable=False),
    # sa.Column('protein', sa.INTEGER(), nullable=False),
    # sa.Column('carb', sa.INTEGER(), nullable=False),
    # sa.Column('fat', sa.INTEGER(), nullable=False),
    # sa.Column('price', sa.INTEGER(), nullable=False),
    # sa.PrimaryKeyConstraint('food_id', 'date')
    # )
    # op.create_index('ix_food_name', 'food', ['name'], unique=False)
    # op.create_index('ix_food_date', 'food', ['date'], unique=False)
    # ### end Alembic commands ###
