"""Rename food_provider to food_vendor

Revision ID: d930e0211fbb
Revises: c3a48756e74f
Create Date: 2025-04-05 11:08:21.773973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd930e0211fbb'
down_revision: Union[str, None] = 'c3a48756e74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("food", "food_provider", new_column_name="food_vendor")
    op.alter_column("jobrun", "food_provider", new_column_name="food_vendor")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('jobrun',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('timestamp', sa.DATETIME(), nullable=False),
    # sa.Column('week', sa.INTEGER(), nullable=False),
    # sa.Column('year', sa.INTEGER(), nullable=False),
    # sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    # sa.Column('food_provider', sa.VARCHAR(), server_default=sa.text("'CITY_FOOD'"), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('food',
    # sa.Column('food_id', sa.INTEGER(), nullable=False),
    # sa.Column('date', sa.DATE(), nullable=False),
    # sa.Column('food_provider', sa.VARCHAR(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('calories', sa.INTEGER(), nullable=False),
    # sa.Column('protein', sa.INTEGER(), nullable=False),
    # sa.Column('carb', sa.INTEGER(), nullable=False),
    # sa.Column('fat', sa.INTEGER(), nullable=False),
    # sa.Column('price', sa.INTEGER(), nullable=False),
    # sa.PrimaryKeyConstraint('food_id', 'date', 'food_provider')
    # )
    # op.create_index('ix_food_new_name', 'food', ['name'], unique=False)
    # op.create_index('ix_food_new_food_provider', 'food', ['food_provider'], unique=False)
    # op.create_index('ix_food_new_date', 'food', ['date'], unique=False)
    # op.create_index('ix_food_name', 'food', ['name'], unique=False)
    # op.create_index('ix_food_food_provider', 'food', ['food_provider'], unique=False)
    # op.create_index('ix_food_date', 'food', ['date'], unique=False)
    # ### end Alembic commands ###
